In [1]:
'''
object classification
object detection
object Tracking
image segmentation
feature matching
video motion analysis
'''

'''
There are two common way to identify the images
1)Gray scale
2)RGB

Image converted in array
'''

'''
Skill Required
1)core Python
2)numpy
3)matplotlib
4)matrix
5)vector
'''

'''
opencv Modules
1)core
2)imgProc
3)imgcodec
4)highgui
5)video
6)calib3d
7)features2D
8)objdetect
9)dnn
10)ml
11)flann
12)photo
13)stiching
14)shape
15)superes
16)videostab
17)viz
'''


'\nopencv Modules\n1)core\n2)imgProc\n3)imgcodec\n4)highgui\n5)video\n6)calib3d\n7)features2D\n8)objdetect\n9)dnn\n10)ml\n11)flann\n12)photo\n13)stiching\n14)shape\n15)superes\n16)videostab\n17)viz\n'


Read and show Image


In [2]:
import cv2 as cv
img = cv.imread('01.jpg') 
cv.imshow("01",img)       
cv.waitKey(0)          
cv.destroyAllWindows()
# cv.destroyWindow()

In [3]:
import cv2 as cv
img = cv.imread('01.jpg') 
cv.imshow("01",img)       
cv.imshow("02",img)       
cv.waitKey(0)          
# cv.destroyAllWindows()
cv.destroyWindow("01")
cv.destroyWindow("02")

Slide Show / carousel slider / resize

In [4]:
import cv2
import numpy as np
import os
img1 = cv2.imread('01.jpg')
img2 = cv2.imread('01.jpg')
# img1 = cv2.resize(img1, (310,410))
h = np.hstack((img1,img2))
v = np.vstack((img1,img2))
vFour = np.vstack((h,h))
# print(img1)
# cv2.imshow('carousel slider', vFour)
list_name = os.listdir(r'C:\Users\USER\code\potato_leaf_disease_detection_project_\OpenCV_Learning\All_About_OpenCV\images')
for name in list_name:
    path = "C:\\Users\\USER\\code\\potato_leaf_disease_detection_project_\\OpenCV_Learning\\All_About_OpenCV\\images"
    img_name = path+"\\"+name
    imgArray = cv2.imread(img_name)
    imgResized = cv2.resize(imgArray,(300,200))
    cv2.imshow("window",imgResized)
    cv2.waitKey(0)
    
print(list_name)
cv2.waitKey(0)
cv2.destroyAllWindows()

['01 - Copy (2).jpg', '01 - Copy (3).jpg', '01 - Copy (4).jpg', '01 - Copy.jpg', '01.jpg', '11.jpg']


In [15]:
import cv2
img = cv2.imread('01.jpg',0)
print(img)
print(img.shape)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 78  80  81 ... 137 132 130]
 [ 80  79  78 ... 138 133 131]
 [ 81  78  76 ... 137 134 132]
 ...
 [149 148 148 ... 203 206 207]
 [149 148 149 ... 202 203 205]
 [149 149 151 ... 200 201 204]]
(300, 300)


text over image


In [28]:
import cv2

# Read the image
img_get = cv2.imread("01.jpg")

# Put text on the image
img_with_text = cv2.putText(
    img=img_get,
    text="Hello World",
    org=(50, 50),
    fontFace=cv2.FONT_HERSHEY_DUPLEX,
    fontScale=3,
    color=(255, 0, 0),
    thickness=3,
    lineType=cv2.LINE_8,
    bottomLeftOrigin=True
)
img_with_text = cv2.putText(
    img=img_get,
    text="Hello World",
    org=(54, 54),
    fontFace=cv2.FONT_HERSHEY_DUPLEX,
    fontScale=3,
    color=(255, 0, 0),
    thickness=3,
    lineType=cv2.LINE_8,
    bottomLeftOrigin=False
)

# Display the image with text
cv2.imshow("image", img_with_text)
cv2.waitKey(0)
cv2.destroyAllWindows()


Draw Line and rectangle


In [36]:
import cv2 
img_1 = cv2.imread("01.jpg")

new_img = cv2.line(
    img = img_1,
    pt1 =(20,80),
    pt2=(200,80),
    color= (0,255,0),
    thickness=3,
    lineType=4
)

cv2.imshow("window", new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
import cv2 
img_1 = cv2.imread("01.jpg")

new_img = cv2.rectangle(
    img = img_1,
    pt1 =(20,50),
    pt2=(200,100),
    color= (0,255,0),
    thickness=3,
    lineType=4
)

cv2.imshow("window", new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()